export const interactiveZonesData = [
    {
        id: 1,
        title: "Магнітна стіна",
        image: "/images/interactiveZone/magnetWall.png",
        imagePosition: "left",
        backgroundColor: "#7c48cc",
        variant: "vertical",
        decorations: ["blobs"],
    },
    {
        id: 2,
        title: "Кінетичний пісок",
        image: "/images/interactiveZone/kineticSand.png",
        imagePosition: "left",
        backgroundColor: "#FFFFFF0F",
        variant: "horizontal",
        decorations: ["star", "glass"],
    },
    {
        id: 3,
        title: "Лего стіна",
        image: "/images/interactiveZone/legoWall.png",
        imagePosition: "left",
        backgroundColor: "#141313",
        variant: "horizontal",
        decorations: ["arrow"],
    },
    {
        id: 4,
        title: "Велика та мала пісочниці",
        image: "/images/interactiveZone/sandbox.png",
        imagePosition: "left",
        backgroundColor: "#5A5A5A",
        variant: "horizontal",
        decorations: ["blobs"],
    },
    {
        id: 5,
        title: "Стіна для малювання",
        image: "/images/interactiveZone/AThing.png",
        imagePosition: "left",
        backgroundColor: "#F8FF69",
        variant: "horizontal",
        decorations: ["bluredElipse"],
    },
    {
        id: 6,
        title: "Інженерні споруди",
        image: "/images/interactiveZone/engineer.png",
        imagePosition: "left",
        backgroundColor: "#141313",
        variant: "horizontal",
        decorations: ["arrow"],
    },
    {
        id: 7,
        title: "Зона фонтанів",
        image: "/images/interactiveZone/fountain.png",
        imagePosition: "left",
        backgroundColor: "#FFFFFF0F",
        variant: "horizontal",
        decorations: ["glass", "star"],
    },
    {
        id: 8,
        title: "Зелена зона",
        image: "/images/interactiveZone/greenZone.png",
        imagePosition: "left",
        backgroundColor: "#8852DE",
        variant: "horizontal",
        decorations: ["noise"],
    },
    {
        id: 9,
        title: "Зона кафе",
        image: "/images/interactiveZone/cafe.png",
        imagePosition: "left",
        backgroundColor: "#5A5A5A",
        variant: "horizontal",
        decorations: ["blobs"],
    },
    {
        id: 10,
        title: "Нудлс стіна",
        image: "/images/interactiveZone/noodlesWall.png",
        imagePosition: "left",
        backgroundColor: "#F6FF3A",
        variant: "horizontal",
        decorations: ["noodle"],
    },
];
